In [1]:
import numpy as np 

In [2]:
np.__version__

'2.2.4'

## Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

5

#### 2D Array

In [12]:
arr2 = np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [14]:
arr2.ndim

2

In [16]:
arr2.shape # (row,columns)

(2, 3)

In [17]:
arr2.dtype

dtype('int64')

In [18]:
arr2.size

6

#### 3D Array

In [26]:
arr3 = np.array([[[1,4,5],[6,7,4]],[[3,5,4],[5,8,7]], [[1,4,5],[6,7,4]]])

In [27]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [29]:
arr2.ndim

2

In [22]:
arr3.shape

(2, 2, 3)

In [23]:
arr3.dtype

dtype('int64')

In [24]:
arr2.size

6

### Create Random Array

In [30]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.28077884, 0.02739836, 0.42755397],
        [0.1368533 , 0.15581838, 0.61168937]],

       [[0.10285454, 0.82504812, 0.03061568],
        [0.60420241, 0.4156962 , 0.98792758]],

       [[0.28600593, 0.06036272, 0.26224902],
        [0.87469504, 0.73061596, 0.22850382]]])

In [31]:
randomArr.dtype

dtype('float64')

In [34]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
zeros.ndim

3

In [37]:
full = np.full((3,2,3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [38]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [39]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [44]:
arr3[0][0][2]

np.int64(5)

In [47]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [48]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [49]:
arr3[1][0][1]

np.int64(5)

In [50]:
arr3[1,0,1]

np.int64(5)

### Update & Delete

In [51]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [52]:
a1

array([[[0.6039505 , 0.10639364],
        [0.01581011, 0.65168318],
        [0.36546982, 0.1313067 ]],

       [[0.80076446, 0.09128801],
        [0.79010797, 0.92498577],
        [0.31025638, 0.59759361]]])

In [53]:
a2

array([[[0.49861545, 0.18387748],
        [0.2298162 , 0.03551742],
        [0.13554304, 0.31934071]],

       [[0.71790453, 0.64647732],
        [0.06253046, 0.27286554],
        [0.57120842, 0.86796499]]])

### Basic Math Operations

In [54]:
np.add(a1,a2)

array([[[1.10256596, 0.29027112],
        [0.24562632, 0.6872006 ],
        [0.50101286, 0.45064741]],

       [[1.518669  , 0.73776533],
        [0.85263844, 1.1978513 ],
        [0.8814648 , 1.4655586 ]]])

In [55]:
np.subtract(a1,a2)

array([[[ 0.10533505, -0.07748383],
        [-0.21400609,  0.61616576],
        [ 0.22992678, -0.18803401]],

       [[ 0.08285993, -0.55518931],
        [ 0.72757751,  0.65212023],
        [-0.26095204, -0.27037138]]])

In [56]:
np.divide(a1,a2)

array([[[ 1.21125509,  0.57861161],
        [ 0.0687946 , 18.34827002],
        [ 2.6963378 ,  0.41118058]],

       [[ 1.11541915,  0.14120837],
        [12.6355686 ,  3.38989587],
        [ 0.54315792,  0.68849967]]])

In [57]:
np.multiply(a1,a2)

array([[[0.30113905, 0.01956339],
        [0.00363342, 0.0231461 ],
        [0.04953689, 0.04193157]],

       [[0.57487244, 0.05901563],
        [0.04940582, 0.25239674],
        [0.17722106, 0.51869033]]])

### Statistical Operations

In [58]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [59]:
sqrt

np.float64(5.0)

In [60]:
abs

np.int64(2)

In [61]:
power

np.int64(256)

In [62]:
log

np.float64(3.2188758248682006)

In [63]:
mins

np.float64(0.015810113073198462)

In [64]:
maxs

np.float64(0.86796498906942)

#### Update

In [65]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [66]:
arr3[0,0,2] = 500

In [67]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [70]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

#### Reshape

In [71]:
arr3.shape

(3, 2, 3)

In [72]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

#### Appending & Insering

In [73]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [76]:
# Create a new array 
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [77]:
appd = np.append(zeros, new_array,axis=0) # axis 0 = row,axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [78]:
# Insert
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [81]:
inserted_array = np.insert(zeros, 1, new_array,axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [82]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.26672461, 0.85592373, 0.0294276 ],
        [0.92049239, 0.53084165, 0.56336234]],

       [[0.07310709, 0.82780688, 0.44084252],
        [0.69650287, 0.65929677, 0.75690732]],

       [[0.50078652, 0.57132644, 0.17187373],
        [0.95051839, 0.90291671, 0.3181325 ]]])

In [84]:
# Delete the array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.92049239, 0.53084165, 0.56336234]],

       [[0.69650287, 0.65929677, 0.75690732]],

       [[0.95051839, 0.90291671, 0.3181325 ]]])

In [85]:
np.save("new_array",arr5)

In [87]:
np.load("new_array.npy")

array([[[0.92049239, 0.53084165, 0.56336234]],

       [[0.69650287, 0.65929677, 0.75690732]],

       [[0.95051839, 0.90291671, 0.3181325 ]]])